frontend:
  - changed-files:
      - any-glob-to-any-file: 'src/**'

etl:
  - changed-files:
      - any-glob-to-any-file: 'etl/**'

data:
  - changed-files:
      - any-glob-to-any-file: 'data/**'

ci:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/**'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'package-lock.json'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - '*.md'
          - 'docs/**'

config:
  - changed-files:
      - any-glob-to-any-file:
          - '*.config.*'
          - 'tsconfig.json'
